AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HarryPotterFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/harrypotterindepthquerybot:latest"
      Timeout: 900
      MemorySize: 1024
      Role: !GetAtt HarryPotterExecutionRole.Arn
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIAPIKey
          LANGCHAIN_API_KEY: !Ref LangChainAPIKey
          LANGCHAIN_PROJECT: !Ref LangChainProject
      Events:
        HarryPotterApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref HarryPotterApiGateway

  HarryPotterApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        AllowOrigin: "'*'"
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
          DataTraceEnabled: true

  HarryPotterExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: arn:aws:s3:::harry-potter-static-file/*
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: arn:aws:ecr:${region}:${accountid}:repository/harrypotterindepthquerybot
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - secretsmanager:GetSecretValue
                Resource: "*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
Parameters:
  OpenAIAPIKey:
    Type: String
    Description: Your OpenAI API Key
  LangChainAPIKey:
    Type: String
    Description: Your LangChain API Key
  LangChainProject:
    Type: String
    Description: Your LangChain Project Name

Outputs:
  ApiUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${HarryPotterApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"